name: encuentrame
description: "Encuentrame.bo MVP"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.4
  amplify_flutter: ^2.10.0
  amplify_auth_cognito: ^2.10.0
  amplify_api: ^2.10.0
  amplify_storage_s3: ^2.10.0
  image_picker: ^1.2.1
  geolocator: ^14.0.2
  uuid: ^4.5.3
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  speech_to_text: ^7.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true